name: MultiArchDockerBuild

on:
  push:
    branches:
      - master
      - develop

jobs:
  build_multi_arch_image:
    name: Build multi-arch Docker image.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment variables
        run:  echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push master (Alpine)
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          target: deploy
          push: true
          tags: |
            fangguisheng/epicgames-freegames:latest
            fangguisheng/epicgames-freegames:$(date +'%Y-%m-%dT%H:%M:%S')
            ghcr.io/fangguisheng/epicgames-freegames-node:latest
            ghcr.io/fangguisheng/epicgames-freegames-node:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            BRANCH=${{ env.GIT_BRANCH }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

      - name: Build and push master (Debian)
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          target: deploy
          push: true
          file: Dockerfile.debian
          tags: |
            fangguisheng/epicgames-freegames:bullseye-slim
            ghcr.io/fangguisheng/epicgames-freegames-node:bullseye-slim
          platforms: linux/amd64
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            BRANCH=${{ env.GIT_BRANCH }}
          cache-from: type=gha,scope=${{ github.workflow }}-Debian
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}-Debian

      - name: Build and push dev
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: docker/build-push-action@v2
        with:
          target: deploy
          push: true
          tags: |
            fangguisheng/epicgames-freegames:dev
            ghcr.io/fangguisheng/epicgames-freegames-node:dev
          platforms: linux/amd64,linux/arm64
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            BRANCH=${{ env.GIT_BRANCH }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
